package dev.feature.chat.presentation

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import dev.core.common.locale.AppLocale
import dev.core.uikit.locale.rememberStrings

/** Chat va xabarlar ekranlarining matnlari. Sukut qiymatlar — inglizcha. */
data class ChatStrings(
    // Suhbat ekrani
    val clubChatSoon: String = "Club chats are coming soon",
    val skippedFiles: (Int) -> String = { "$it file(s) weren't sent — the video is longer than 3 minutes or the format isn't supported." },
    val nothingToCopy: String = "There's no copyable text in these messages",
    val copied: String = "Copied",
    val startConversation: String = "Write a message to start the conversation",
    val videoProcessing: String = "The video is still processing",
    val downloadSoon: String = "File download is coming soon",
    val typing: String = "typing…",
    val connecting: String = "connecting…",
    val message: String = "Message",
    val resend: String = "Send again",
    val selectText: String = "Select text",
    val report: String = "Report",
    val disconnect: String = "Remove connection",
    val block: String = "Block",
    val cancel: String = "Cancel",
    val disconnectBody: String = "After disconnecting you can't write in this chat, but old messages stay.",
    val disconnectConfirm: String = "Remove",
    val blockBody: (String) -> String = { "$it will be blocked: the connection is removed and neither of you can write to the other." },
    val reportTitle: (String) -> String = { "Report: $it" },
    val reportMessage: String = "Report this message",
    val reportNote: String = "Comment (optional)",
    val reportSend: String = "Send",
    val menu: String = "Menu",
    val voiceCall: String = "Voice call",
    val videoCall: String = "Video call",
    val cancelSelection: String = "Cancel selection",
    val selectedCount: (Int) -> String = { "$it selected" },
    val copy: String = "Copy",
    val more: String = "More",
    val delete: String = "Delete",
    val deleteCount: (Int) -> String = { "Delete $it message(s)" },
    val deleteConfirm: String = "Are you sure you want to delete these messages?",
    val deleteForPeer: (String) -> String = { "Delete for $it too" },
    val deleteForPeerNote: String = "You can only delete the other person's messages on your own side.",
    val selectTextHint: String = "Press and hold the text you need, then tap the «Copy» button that appears.",
    val copyAll: String = "Copy all",
    val close: String = "Close",
    val messageDeleted: String = "Message deleted",

    // Qo'ng'iroq yozuvlari
    val missedCall: String = "Missed call",
    val declinedCall: String = "Declined call",
    val canceledCall: String = "Canceled call",
    val call: String = "Call",
    val callWithDuration: (String) -> String = { "Call · $it" },

    // Yozish paneli
    val attachMedia: String = "Attach a photo or video",
    val messageHint: String = "Write a message…",
    val stickers: String = "Stickers",
    val send: String = "Send",
    val stop: String = "Stop",
    val recordVoice: String = "Record voice",

    // Shikoyat sabablari
    val reasonSpam: String = "Spam",
    val reasonFraud: String = "Fraud",
    val reasonHarassment: String = "Harassment",
    val reasonInappropriate: String = "Inappropriate",
    val reasonOther: String = "Other",

    // Galereya varag'i
    val maxAtOnce: (Int) -> String = { "$it — that's the max at once" },
    val selectedItems: (Int, String) -> String = { n, kind -> "$n $kind selected" },
    val onlySelectedShown: String = "Only the items you picked are shown",
    val showAll: String = "Show all",
    val camera: String = "Camera",
    val galleryPermissionTitle: String = "Gallery access needed",
    val galleryPermissionDenied: String = "Permission was denied. Enable it in Settings and your photos will show up here — " +
        "or use «Gallery» below to pick without permission.",
    val galleryPermissionAsk: String = "Allow access so your photos appear here. If you'd rather not, " +
        "«Gallery» below works without permission.",
    val openSettings: String = "Open Settings",
    val grantPermission: String = "Allow",
    val addCaption: String = "Add a caption…",
    val gallery: String = "Gallery",
    val file: String = "File",
    val videoNote: String = "Video message",
    val kindPhotos: String = "photo(s)",
    val kindVideos: String = "video(s)",
    val kindItems: String = "item(s)",

    // Video ko'rish
    val video: String = "Video",
    val videoNoteTrimmed: String = "Video messages are trimmed to 1 minute",

    // Suhbatdosh varag'i bo'limlari
    val tabPosts: String = "Posts",
    val tabMedia: String = "Media",
    val tabFiles: String = "Files",
    val tabLinks: String = "Links",

    // Xabarlar ro'yxati
    val messages: String = "Messages",
    val archive: String = "Archive",
    val personal: String = "Personal",
    val clubs: String = "Clubs",
    val searchHint: String = "Search chats or clubs",
    val nothingFoundFor: (String) -> String = { "Nothing found for «$it»" },
    val noArchivedChats: String = "No archived chats.",
    val startFromSection: (String) -> String = { "Start writing from the $it section." },
    val clubsSoon: String = "Clubs are coming soon.",
    val unarchive: String = "Unarchive",
    val archiveAction: String = "Archive",
    val newChat: String = "New chat",
    val search: String = "Search",
    val membersCount: (Int) -> String = { "$it members" },
    val notMember: String = "Not a member",
    val join: String = "Join",
    val joinedClub: String = "You joined the club",
    val leftClub: String = "You left the club",
    val connectionRemoved: String = "Connection removed",
    val blocked: String = "Blocked",
    val reportAccepted: String = "Your report has been received",

    // Ro'yxatdagi oxirgi xabar ko'rinishi
    val previewPhoto: String = "📷 Photo",
    val previewVideo: String = "🎬 Video",
    val previewVideoNote: String = "⭕️ Video message",
    val previewVoice: String = "🎤 Voice message",
    val previewFile: String = "📎 File",
    val previewSticker: (String) -> String = { "$it Sticker" },
    val previewCall: (String) -> String = { "📞 $it" },

    // Sana yorliqlari
    val today: String = "Today",
    val yesterday: String = "Yesterday",
    val lastSeenAt: (String) -> String = { "last seen $it" },
    val lastSeenYesterday: (String) -> String = { "yesterday $it" },

    // Media paneli
    val searchStickers: String = "Search stickers…",
    val noStickersFor: (String) -> String = { "No stickers found for «$it»." },
    val searchGifs: String = "Search GIFs…",
    val noGifs: String = "No GIFs found.",
    val noGifsFor: (String) -> String = { "No GIFs found for «$it»." },
    val retry: String = "Try again",
    val sendFailedRetry: String = "not sent · tap to retry",
    val play: String = "Play",
    val voiceMessage: String = "Voice message",
)

private val ChatEn = ChatStrings()

private val ChatRu = ChatStrings(
    clubChatSoon = "Чаты клубов скоро появятся",
    skippedFiles = { "$it файл(ов) не отправлено — видео длиннее 3 минут или формат не поддерживается." },
    nothingToCopy = "В этих сообщениях нет текста для копирования",
    copied = "Скопировано",
    startConversation = "Напишите сообщение, чтобы начать разговор",
    videoProcessing = "Видео ещё обрабатывается",
    downloadSoon = "Скачивание файлов скоро появится",
    typing = "печатает…",
    connecting = "соединение…",
    message = "Сообщение",
    resend = "Отправить снова",
    selectText = "Выделить текст",
    report = "Пожаловаться",
    disconnect = "Удалить из друзей",
    block = "Заблокировать",
    cancel = "Отмена",
    disconnectBody = "После удаления связи вы не сможете писать в этот чат, но старые сообщения останутся.",
    disconnectConfirm = "Удалить",
    blockBody = { "$it будет заблокирован: связь удалится, и вы не сможете писать друг другу." },
    reportTitle = { "Жалоба: $it" },
    reportMessage = "Жалоба на сообщение",
    reportNote = "Комментарий (необязательно)",
    reportSend = "Отправить",
    menu = "Меню",
    voiceCall = "Голосовой звонок",
    videoCall = "Видеозвонок",
    cancelSelection = "Отменить выделение",
    selectedCount = { "Выбрано: $it" },
    copy = "Копировать",
    more = "Ещё",
    delete = "Удалить",
    deleteCount = { "Удалить $it сообщ." },
    deleteConfirm = "Действительно удалить эти сообщения?",
    deleteForPeer = { "Удалить и у $it" },
    deleteForPeerNote = "Сообщения собеседника можно удалить только у себя.",
    selectTextHint = "Зажмите нужный текст, затем нажмите появившуюся кнопку «Copy».",
    copyAll = "Копировать всё",
    close = "Закрыть",
    messageDeleted = "Сообщение удалено",

    missedCall = "Пропущенный звонок",
    declinedCall = "Отклонённый звонок",
    canceledCall = "Отменённый звонок",
    call = "Звонок",
    callWithDuration = { "Звонок · $it" },

    attachMedia = "Прикрепить фото или видео",
    messageHint = "Напишите сообщение…",
    stickers = "Стикеры",
    send = "Отправить",
    stop = "Стоп",
    recordVoice = "Записать голос",

    reasonSpam = "Спам",
    reasonFraud = "Мошенничество",
    reasonHarassment = "Оскорбления",
    reasonInappropriate = "Неприемлемое",
    reasonOther = "Другое",

    maxAtOnce = { "$it — это максимум за раз" },
    selectedItems = { n, kind -> "Выбрано $n $kind" },
    onlySelectedShown = "Показаны только выбранные вами",
    showAll = "Показать все",
    camera = "Камера",
    galleryPermissionTitle = "Нужен доступ к галерее",
    galleryPermissionDenied = "Доступ запрещён. Включите его в настройках, и фото появятся здесь — " +
        "либо выберите через «Галерею» ниже без разрешения.",
    galleryPermissionAsk = "Разрешите доступ, чтобы фото появились здесь. Если не хотите — " +
        "«Галерея» ниже работает и без разрешения.",
    openSettings = "Открыть настройки",
    grantPermission = "Разрешить",
    addCaption = "Добавить подпись…",
    gallery = "Галерея",
    file = "Файл",
    videoNote = "Видеосообщение",
    kindPhotos = "фото",
    kindVideos = "видео",
    kindItems = "шт.",

    video = "Видео",
    videoNoteTrimmed = "Видеосообщение обрезается до 1 минуты",

    tabPosts = "Посты",
    tabMedia = "Медиа",
    tabFiles = "Файлы",
    tabLinks = "Ссылки",

    messages = "Сообщения",
    archive = "Архив",
    personal = "Личные",
    clubs = "Клубы",
    searchHint = "Поиск чата или клуба",
    nothingFoundFor = { "По запросу «$it» ничего не найдено" },
    noArchivedChats = "Нет архивированных чатов.",
    startFromSection = { "Начните переписку из раздела $it." },
    clubsSoon = "Клубы скоро появятся.",
    unarchive = "Из архива",
    archiveAction = "В архив",
    newChat = "Новый чат",
    search = "Поиск",
    membersCount = { "$it участников" },
    notMember = "Не участник",
    join = "Вступить",
    joinedClub = "Вы вступили в клуб",
    leftClub = "Вы вышли из клуба",
    connectionRemoved = "Связь удалена",
    blocked = "Заблокирован",
    reportAccepted = "Ваша жалоба принята",

    previewPhoto = "📷 Фото",
    previewVideo = "🎬 Видео",
    previewVideoNote = "⭕️ Видеосообщение",
    previewVoice = "🎤 Голосовое",
    previewFile = "📎 Файл",
    previewSticker = { "$it Стикер" },
    previewCall = { "📞 $it" },

    today = "Сегодня",
    yesterday = "Вчера",
    lastSeenAt = { "был(а) в сети $it" },
    lastSeenYesterday = { "вчера $it" },

    searchStickers = "Поиск стикеров…",
    noStickersFor = { "По запросу «$it» стикеры не найдены." },
    searchGifs = "Поиск GIF…",
    noGifs = "GIF не найдены.",
    noGifsFor = { "По запросу «$it» GIF не найдены." },
    retry = "Повторить",
    sendFailedRetry = "не отправлено · нажмите, чтобы повторить",
    play = "Прослушать",
    voiceMessage = "Голосовое сообщение",
)

private val ChatUz = ChatStrings(
    clubChatSoon = "Klub suhbati tez orada ochiladi",
    skippedFiles = { "$it ta fayl yuborilmadi — video 3 daqiqadan uzun yoki format qo'llab-quvvatlanmaydi." },
    nothingToCopy = "Bu xabarlarda nusxa olinadigan matn yo'q",
    copied = "Nusxa olindi",
    startConversation = "Xabar yozib, suhbatni boshlang",
    videoProcessing = "Video hali tayyorlanmoqda",
    downloadSoon = "Faylni yuklab olish tez orada",
    typing = "yozmoqda…",
    connecting = "ulanmoqda…",
    message = "Xabar",
    resend = "Qayta yuborish",
    selectText = "Matnni belgilash",
    report = "Shikoyat qilish",
    disconnect = "Bog'lanishni uzish",
    block = "Bloklash",
    cancel = "Bekor",
    disconnectBody = "Bog'lanish uzilgach bu suhbatga yozolmaysiz, lekin eski xabarlar qoladi.",
    disconnectConfirm = "Uzish",
    blockBody = { "$it bloklanadi: bog'lanish o'chadi va ikkalangiz bir-biringizga yozolmaysiz." },
    reportTitle = { "Shikoyat: $it" },
    reportMessage = "Xabar ustidan shikoyat",
    reportNote = "Izoh (ixtiyoriy)",
    reportSend = "Yuborish",
    menu = "Menyu",
    voiceCall = "Ovozli qo'ng'iroq",
    videoCall = "Video qo'ng'iroq",
    cancelSelection = "Belgilashni bekor qilish",
    selectedCount = { "$it ta tanlandi" },
    copy = "Nusxa olish",
    more = "Yana",
    delete = "O'chirish",
    deleteCount = { "$it ta xabarni o'chirish" },
    deleteConfirm = "Haqiqatan ham bu xabarlarni o'chirmoqchimisiz?",
    deleteForPeer = { "$it uchun ham o'chirilsin" },
    deleteForPeerNote = "Suhbatdoshning xabarlarini faqat o'zingizda o'chira olasiz.",
    selectTextHint = "Kerakli gapni bosib turib belgilang, so'ng chiqqan «Copy» tugmasini bosing.",
    copyAll = "Hammasini nusxalash",
    close = "Yopish",
    messageDeleted = "Xabar o'chirildi",

    missedCall = "Javobsiz qo'ng'iroq",
    declinedCall = "Rad etilgan qo'ng'iroq",
    canceledCall = "Bekor qilingan qo'ng'iroq",
    call = "Qo'ng'iroq",
    callWithDuration = { "Qo'ng'iroq · $it" },

    attachMedia = "Rasm yoki video biriktirish",
    messageHint = "Xabar yozing…",
    stickers = "Stikerlar",
    send = "Yuborish",
    stop = "To'xtatish",
    recordVoice = "Ovoz yozish",

    reasonSpam = "Spam",
    reasonFraud = "Firibgarlik",
    reasonHarassment = "Haqorat",
    reasonInappropriate = "Nomaqbul",
    reasonOther = "Boshqa",

    maxAtOnce = { "$it ta — bir martada shuncha" },
    selectedItems = { n, kind -> "$n ta $kind tanlandi" },
    onlySelectedShown = "Faqat siz tanlagan rasmlar ko'rinmoqda",
    showAll = "Barchasini ko'rsatish",
    camera = "Kamera",
    galleryPermissionTitle = "Galereyaga ruxsat kerak",
    galleryPermissionDenied = "Ruxsat rad etilgan. Sozlamalardan yoqsangiz rasmlar shu yerda ko'rinadi — " +
        "yoki pastdagi «Galereya» orqali ruxsatsiz tanlang.",
    galleryPermissionAsk = "Rasmlaringiz shu yerda ko'rinishi uchun ruxsat bering. Xohlamasangiz — " +
        "pastdagi «Galereya» ruxsatsiz ham ishlaydi.",
    openSettings = "Sozlamalarni ochish",
    grantPermission = "Ruxsat berish",
    addCaption = "Izoh qo'shish…",
    gallery = "Galereya",
    file = "Fayl",
    videoNote = "Video xabar",
    kindPhotos = "rasm",
    kindVideos = "video",
    kindItems = "element",

    video = "Video",
    videoNoteTrimmed = "Video xabar 1 daqiqagacha qisqartiriladi",

    tabPosts = "Postlar",
    tabMedia = "Media",
    tabFiles = "Fayllar",
    tabLinks = "Havolalar",

    messages = "Xabarlar",
    archive = "Arxiv",
    personal = "Shaxsiy",
    clubs = "Klublar",
    searchHint = "Suhbat yoki klub qidiring",
    nothingFoundFor = { "«$it» bo'yicha hech nima topilmadi" },
    noArchivedChats = "Arxivga ko'chirilgan suhbat yo'q.",
    startFromSection = { "$it bo'limidan yozishni boshlang." },
    clubsSoon = "Klublar tez orada qo'shiladi.",
    unarchive = "Arxivdan chiqarish",
    archiveAction = "Arxivlash",
    newChat = "Yangi suhbat",
    search = "Qidirish",
    membersCount = { "$it a'zo" },
    notMember = "A'zosiz",
    join = "Qo'shilish",
    joinedClub = "Klubga qo'shildingiz",
    leftClub = "Klubdan chiqdingiz",
    connectionRemoved = "Bog'lanish uzildi",
    blocked = "Bloklandi",
    reportAccepted = "Shikoyatingiz qabul qilindi",

    previewPhoto = "📷 Rasm",
    previewVideo = "🎬 Video",
    previewVideoNote = "⭕️ Video xabar",
    previewVoice = "🎤 Ovozli xabar",
    previewFile = "📎 Fayl",
    previewSticker = { "$it Stiker" },
    previewCall = { "📞 $it" },

    today = "Bugun",
    yesterday = "Kecha",
    lastSeenAt = { "oxirgi faollik $it" },
    lastSeenYesterday = { "kecha $it" },

    searchStickers = "Stiker qidirish…",
    noStickersFor = { "«$it» bo'yicha stiker topilmadi." },
    searchGifs = "GIF qidirish…",
    noGifs = "GIF topilmadi.",
    noGifsFor = { "«$it» bo'yicha GIF topilmadi." },
    retry = "Qayta urinish",
    sendFailedRetry = "yuborilmadi · qayta urinish",
    play = "Eshitish",
    voiceMessage = "Ovozli xabar",
)

@Composable
@ReadOnlyComposable
internal fun chatStrings(): ChatStrings = rememberStrings(ChatEn, ChatRu, ChatUz)

/** ViewModel va sof formatlash funksiyalari uchun — Compose'dan tashqarida. */
internal fun chatStringsNow(): ChatStrings = AppLocale.pick(ChatEn, ChatRu, ChatUz)
